<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AiChatController;
use App\Http\Controllers\Api\AiKnowledgeEntryController;
use App\Http\Controllers\Api\AdminAccountController;
use App\Http\Controllers\Api\AdminNotificationController;
use App\Http\Controllers\Api\BannerController;
use App\Http\Controllers\Api\BrandController;
use App\Http\Controllers\Api\CartController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CheckoutController;
use App\Http\Controllers\Api\ColorController;
use App\Http\Controllers\Api\EventController;
use App\Http\Controllers\Api\FavoriteController;
use App\Http\Controllers\Api\GoogleReviewController;
use App\Http\Controllers\Api\MeasurementController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\QuotationRequestController;
use App\Http\Controllers\Api\SeoController;
use App\Http\Controllers\Api\SizeOptionController;
use App\Http\Controllers\Api\SubCategoryController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::post('/customer/register', [AuthController::class, 'customerRegister'])->middleware('throttle:5,1');
Route::post('/customer/login', [AuthController::class, 'customerLogin'])->middleware('throttle:10,1');
Route::post('/admin/register', [AuthController::class, 'adminRegister'])->middleware('throttle:5,1');
Route::post('/admin/login', [AuthController::class, 'adminLogin'])->middleware('throttle:10,1');
Route::post('/register', [AuthController::class, 'customerRegister'])->middleware('throttle:5,1');
Route::post('/login', [AuthController::class, 'customerLogin'])->middleware('throttle:10,1');
Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
Route::post('/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');
Route::get('/public/banners', [BannerController::class, 'publicIndex']);
Route::get('/public/brands', [BrandController::class, 'publicIndex']);
Route::get('/public/categories', [CategoryController::class, 'publicIndex']);
Route::get('/public/sub-categories', [SubCategoryController::class, 'publicIndex']);
Route::get('/public/products', [ProductController::class, 'publicIndex']);
Route::get('/public/product-filters', [ProductController::class, 'publicFilters']);
Route::get('/public/products/{productSlug}', [ProductController::class, 'publicShowBySlug']);
Route::get('/public/categories/{slug}', [CategoryController::class, 'publicShow']);
Route::get('/public/categories/{categorySlug}/sub-categories/{subCategorySlug}/products', [ProductController::class, 'publicIndexBySubCategory']);
Route::get('/public/categories/{categorySlug}/sub-categories/{subCategorySlug}/products/{productSlug}', [ProductController::class, 'publicShow']);
Route::get('/public/events', [EventController::class, 'publicIndex']);
Route::get('/public/google-reviews', [GoogleReviewController::class, 'publicIndex']);
Route::get('/public/seo', [SeoController::class, 'publicShow']);
Route::post('/public/checkout/quote', [CheckoutController::class, 'guestQuote']);
Route::post('/public/quotation-requests', [QuotationRequestController::class, 'publicStore']);
Route::post('/public/ai-chat', [AiChatController::class, 'respond'])->middleware('throttle:20,1');

Route::middleware('auth:sanctum')->group(function (): void {
    Route::get('/user', fn (Request $request) => $request->user());
    Route::get('/profile', [ProfileController::class, 'show']);
    Route::put('/profile', [ProfileController::class, 'update']);
    Route::get('/cart', [CartController::class, 'index']);
    Route::post('/cart', [CartController::class, 'store']);
    Route::patch('/cart/{cartItem}', [CartController::class, 'update']);
    Route::delete('/cart/{cartItem}', [CartController::class, 'destroy']);
    Route::delete('/cart', [CartController::class, 'clear']);
    Route::post('/cart/merge', [CartController::class, 'merge']);
    Route::post('/checkout/quote', [CheckoutController::class, 'quote']);
    Route::post('/checkout/orders', [OrderController::class, 'store']);
    Route::get('/favorites', [FavoriteController::class, 'index']);
    Route::post('/favorites', [FavoriteController::class, 'store']);
    Route::delete('/favorites/{product}', [FavoriteController::class, 'destroy']);
    Route::post('/logout', [AuthController::class, 'logout']);
});

Route::middleware(['auth:sanctum', 'admin.approved'])->group(function (): void {
    Route::get('/users', [UserController::class, 'index']);
    Route::apiResource('/categories', CategoryController::class);
    Route::apiResource('/sub-categories', SubCategoryController::class);
    Route::apiResource('/brands', BrandController::class);
    Route::apiResource('/colors', ColorController::class);
    Route::apiResource('/measurements', MeasurementController::class);
    Route::apiResource('/size-options', SizeOptionController::class);
    Route::apiResource('/products', ProductController::class);
    Route::apiResource('/events', EventController::class);
    Route::apiResource('/banners', BannerController::class);
    Route::post('/banners/reorder', [BannerController::class, 'reorder']);
    Route::get('/seo', [SeoController::class, 'index']);
    Route::put('/seo/{seoPage}', [SeoController::class, 'update']);
    Route::put('/seo-robots', [SeoController::class, 'updateRobots']);
    Route::get('/quotation-requests', [QuotationRequestController::class, 'index']);
    Route::get('/quotation-requests/{quotationRequest}', [QuotationRequestController::class, 'show']);
    Route::patch('/quotation-requests/{quotationRequest}', [QuotationRequestController::class, 'update']);
    Route::delete('/quotation-requests/{quotationRequest}', [QuotationRequestController::class, 'destroy']);
    Route::get('/orders', [OrderController::class, 'index']);
    Route::get('/orders/{order}', [OrderController::class, 'show']);
    Route::patch('/orders/{order}', [OrderController::class, 'update']);
    Route::get('/admin-notifications', [AdminNotificationController::class, 'index']);
    Route::apiResource('/ai-knowledge', AiKnowledgeEntryController::class);
});

Route::middleware(['auth:sanctum', 'super.admin'])->group(function (): void {
    Route::get('/admin-accounts', [AdminAccountController::class, 'index']);
    Route::patch('/admin-accounts/{user}/status', [AdminAccountController::class, 'updateStatus']);
});
